name: Rust WASM CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Install system dependencies for ALSA
      - name: Install ALSA library
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
          
      # Install the latest Rust stable toolchain + components
      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true  # Make this toolchain default

      # Show cargo version (just for logging)
      - name: Check Cargo version
        run: cargo --version

      # Check formatting
      - name: Check formatting with rustfmt
        run: cargo fmt -- --check

      # Run clippy linter
      - name: Lint with clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

      # Run tests
      - name: Run tests
        run: cargo test --all-features --all-targets

      # Install wasm-pack
      - name: Install wasm-pack
        run: cargo install wasm-pack

      # Build your WASM package
      - name: Build with wasm-pack
        run: wasm-pack build --target web